name: Sync Fork with Release

on:
  schedule:
    - cron: '30 11-19 * * MON-FRI' #Runs every 30th minute past the 11, 12, 13, 14, 15, 16, 17, 18 and 19th hour on Mon, Tue, Wed, Thu and Fri.
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: quartetcipp
          base: master
          head: master
          token: ${{secrets.GITHUBACTIONTOKEN}}
