name: Sync To Production
on:
  push:
    branches:
      - UAT

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
          FROM_BRANCH: "UAT"
          TO_BRANCH: "Production"
          PULL_REQUEST_TITLE: "CIPP-API Update To Production"
          PULL_REQUEST_BODY: "CIPP-API/UAT has a new update for CIPP-API/Production Please Review/test https://cipp-uat.quartetservice.com and approve if everything is working." 
      - name: Send email
        id: send_email
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # SMTP server address
          server_address: quartetservice-com.mail.protection.outlook.com.
          
          # SMTP server port
          server_port: 25
          
          # Subject of mail message
          subject: "CIPP-API Update Pending Approval (Pull Request ${{ steps.pull.PULL_REQUEST_NUMBER }})"
          
          # Recipients mail addresses (separated with comma)
          to: lbrunton@quartetservice.com
          
          # Full name of mail sender (might be with an email address specified in <>)
          from: CIPP-API@github.quartetservice.com
          
          # Whether this connection use TLS (default is true if server_port is 465)
          #secure:
          
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: "Please Test https://cipp-uat.quartetservice.com and validate it's working then go to ${{ steps.pull.PULL_REQUEST_URL }}"
          
          # HTML body of mail message (might be a filename prefixed with file:// to read from)
          #html_body: # optional
          
          # Carbon copy recipients (separated with comma)
          #cc: # optional
          
          # Blind carbon copy recipients (separated with comma)
          #bcc: # optional
          
          # An email address that will appear on the Reply-To field
          #reply_to: # optional
          
          # The Message-ID this message is replying to
          #in_reply_to: # optional
          
          # Allow unsigned/invalid certificates
          #ignore_cert: # optional
          
          # Convert body from Markdown to HTML (set content_type input as text/html too)
          #convert_markdown: # optional
          
          # Files that will be added to mail message attachments (separated with comma)
          #attachments: # optional
          
          # Set Priority level for the mail message to 'high', 'normal' (default) or 'low'
          #priority: # optional
