name: Sync To UAT
on:
  push:
    branches:
      - master
  workflow_dispatch: # on button click

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: UAT
          token: ${{secrets.GITHUBACTIONTOKEN}}
          force: true
